<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: https://leo-editor.github.io/leo-editor/leo_toc.html -->
<leo_file xmlns:leo="https://leo-editor.github.io/leo-editor/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="zoomq.20230511210425.1"><vh>tools</vh>
<v t="zoomq.20250514123043.1"><vh>@auto custom.css</vh></v>
<v t="zoomq.20250514154556.1"><vh>_pandoc2reveal.sh</vh></v>
</v>
<v t="zoomq.20220612212104.1"><vh>slides/</vh>
<v t="zoomq.20250515211657.1"><vh>public</vh>
<v t="zoomq.20230511211522.1"><vh>@auto index.md</vh></v>
<v t="zoomq.20231211205711.1"><vh>@auto AIGCxZh2life3.md</vh></v>
</v>
<v t="zoomq.20230511212243.1"><vh>Chaos42</vh>
<v t="zoomq.20250805112853.1"><vh>@auto web3cryptcoin101.md</vh></v>
<v t="zoomq.20231211205711.1"></v>
<v t="zoomq.20230511211522.1"></v>
<v t="zoomq.20240521193237.1"><vh>@auto effecitc0.md</vh></v>
<v t="zoomq.20240704202345.1"><vh>@auto effect4pandsc0.md</vh></v>
<v t="zoomq.20250320214559.1"><vh>Hedy.org</vh>
<v t="zoomq.20240522155614.1"><vh>@auto hedy4cd120c1.md</vh></v>
<v t="zoomq.20240527170001.1"><vh>@auto hedy4cd120c2.md</vh></v>
<v t="zoomq.20240529075033.1"><vh>@auto hedy4cd120c3.md</vh></v>
<v t="zoomq.20240531153951.1"><vh>@auto hedy4cd120c4.md</vh></v>
<v t="zoomq.20240603151307.1"><vh>@auto hedy4cd120c5.md</vh></v>
<v t="zoomq.20240603152118.1"><vh>@auto hedy4cd120c6.md</vh></v>
<v t="zoomq.20240603153255.1"><vh>@auto hedy4cd120c7.md</vh></v>
<v t="zoomq.20240616232927.1"><vh>@auto hedy4cd120c8.md</vh></v>
</v>
<v t="zoomq.20230615195832.1"><vh>@auto c42d-oldeath.md</vh></v>
<v t="zoomq.20230622142203.1"><vh>@auto c42d-liveaid.md</vh></v>
<v t="zoomq.20230621144251.1"><vh>@auto c42d-fsm4gnu.md</vh></v>
<v t="zoomq.20230620092202.1"><vh>@auto c42d-mayfly.md</vh></v>
<v t="zoomq.20230619201734.1"><vh>@auto c42d-dself.md</vh></v>
<v t="zoomq.20230618105034.1"><vh>@auto c42d-helen.md</vh></v>
<v t="zoomq.20230617154539.1"><vh>@auto c42d-smoot.md</vh></v>
<v t="zoomq.20230616145017.1"><vh>@auto c42d-fool2skyline.md</vh></v>
<v t="zoomq.20230614162243.1"><vh>@auto c42d-slide-takahashi.md</vh></v>
<v t="zoomq.20230607222048.1"><vh>@auto c42d-floss-meat.md</vh></v>
<v t="zoomq.20230606205742.1"><vh>@auto c42d-gim.md</vh></v>
<v t="zoomq.20230604151842.1"><vh>@auto c42d-ssDragons.md</vh></v>
<v t="zoomq.20230511212243.46"><vh>@auto c42d-kingdem.md</vh></v>
<v t="zoomq.20230528113303.1"><vh>@auto c42d-22cc.md</vh></v>
<v t="zoomq.20230528161626.1"><vh>@auto c42d-odd1life.md</vh></v>
<v t="zoomq.20230528102757.1"><vh>@auto c42gpt2how.md</vh></v>
</v>
<v t="zoomq.20220612212104.2"><vh>speech</vh>
<v t="zoomq.20230609220205.1"><vh>@auto GIAC23PKMtools.md</vh></v>
<v t="zoomq.20230320012618.1"><vh>@auto 521Pythonic.md</vh></v>
<v t="zoomq.20230519192134.1"><vh>@auto a16zWEB3DAO10.md</vh></v>
<v t="zoomq.20221224143533.1"><vh>@auto a16zWEB3DAO9.md</vh></v>
<v t="zoomq.20221209221640.1"><vh>@auto COSCON22camp101.md</vh></v>
<v t="zoomq.20220925102350.1"><vh>@auto OSCAR22PEP.md</vh></v>
<v t="zoomq.20220612212104.3"><vh>@auto ctalk220908gdgzh.md</vh></v>
<v t="zoomq.20220831213740.1"><vh>@auto coscon21dama.md</vh></v>
<v t="zoomq.20220612212104.64"><vh>@auto coscon21zh.md</vh></v>
<v t="zoomq.20220612212104.131"><vh>@auto coscup21.md</vh></v>
<v t="zoomq.20220612212104.220"><vh>@auto iscas425.md</vh></v>
<v t="zoomq.20220612212104.309"><vh>@auto geek2py.md</vh></v>
<v t="zoomq.20220612212104.409"><vh>@auto oss20doc.md</vh></v>
<v t="zoomq.20220612212104.487"><vh>@auto openi19sz.md</vh></v>
<v t="zoomq.20220612212104.560"><vh>@auto pycon19nn.md</vh></v>
<v t="zoomq.20220612212104.635"><vh>@auto coscon19sh.md</vh></v>
<v t="zoomq.20220612212104.704"><vh>@auto atl2china.md</vh></v>
</v>
<v t="zoomq.20220612212104.6189"><vh>_d0d.py</vh>
<v t="zoomq.20220612212104.6190"><vh>@auto d0d0ch.md</vh></v>
<v t="zoomq.20220612212104.6204"><vh>@auto d0d1ch.md</vh></v>
<v t="zoomq.20220612212104.6218"><vh>@auto d0d2ch.md</vh></v>
<v t="zoomq.20220612212104.6231"><vh>@auto d0d3ch.md</vh></v>
<v t="zoomq.20220612212104.6245"><vh>@auto d0d4ch.md</vh></v>
<v t="zoomq.20220612212104.6259"><vh>@auto d0d5ch.md</vh></v>
<v t="zoomq.20220612212104.6273"><vh>@auto d0d6ch.md</vh></v>
<v t="zoomq.20220612212104.6287"><vh>@auto d0d7ch.md</vh></v>
</v>
<v t="zoomq.20230315164050.1"><vh>QPythoniCamp</vh>
<v t="zoomq.20220612212104.792"><vh>@auto QPicoCar_mov101.md</vh></v>
<v t="zoomq.20230315164050.2"><vh>@auto QPyCamp109.md</vh></v>
<v t="zoomq.20230315164050.23"><vh>@auto QPyCamp108.md</vh></v>
<v t="zoomq.20230315164050.44"><vh>@auto QPyCamp107.md</vh></v>
<v t="zoomq.20230315164050.63"><vh>@auto QPyCamp106.md</vh></v>
<v t="zoomq.20230315164050.81"><vh>@auto QPyCamp105.md</vh></v>
<v t="zoomq.20230315164050.99"><vh>@auto QPyCamp104.md</vh></v>
<v t="zoomq.20230315164050.116"><vh>@auto QPyCamp103.md</vh></v>
<v t="zoomq.20230315164050.133"><vh>@auto QPyCamp102.md</vh></v>
<v t="zoomq.20230315164050.150"><vh>@auto QPyCamp101.md</vh></v>
<v t="zoomq.20230315164050.170"><vh>@auto QPyCamp10g.md</vh></v>
</v>
<v t="zoomq.20220612212104.3896"><vh>DuouD</vh>
<v t="zoomq.20220612212104.3897"><vh>@auto DUO101.md</vh></v>
</v>
<v t="zoomq.20220612212104.3919"><vh>_duw</vh>
<v t="zoomq.20220612212104.3920"><vh>@auto duw180.md</vh></v>
<v t="zoomq.20220612212104.3974"><vh>@auto duw173.md</vh></v>
<v t="zoomq.20220612212104.4034"><vh>@auto duw152.md</vh></v>
<v t="zoomq.20220612212104.4085"><vh>@auto duw150.md</vh></v>
<v t="zoomq.20220612212104.4139"><vh>@auto duw146.md</vh></v>
<v t="zoomq.20220612212104.4180"><vh>@auto duw141.md</vh></v>
<v t="zoomq.20220612212104.4369"><vh>@auto duw140.md</vh></v>
<v t="zoomq.20220612212104.4563"><vh>Yazi 架构</vh></v>
<v t="zoomq.20220612212104.4564"><vh>@auto duw139.md</vh></v>
<v t="zoomq.20220612212104.4758"><vh>@auto duw138.md</vh></v>
<v t="zoomq.20220612212104.4952"><vh>SET4 演化</vh></v>
<v t="zoomq.20220612212104.4953"><vh>@auto duw137.md</vh></v>
<v t="zoomq.20220612212104.5142"><vh>@auto duw131.md</vh></v>
<v t="zoomq.20220612212104.5319"><vh>@auto duw128.md</vh></v>
<v t="zoomq.20220612212104.5492"><vh>@auto duw127.md</vh></v>
<v t="zoomq.20220612212104.5662"><vh>@auto duw120.md</vh></v>
<v t="zoomq.20220612212104.5832"><vh>@auto duw119.md</vh></v>
<v t="zoomq.20220612212104.6004"><vh>@auto duw118.md</vh></v>
<v t="zoomq.20220612212104.6169"><vh>自怼圈</vh>
<v t="zoomq.20220612212104.6170"><vh>知识星球</vh></v>
<v t="zoomq.20220612212104.6171"><vh>小密圈</vh></v>
<v t="zoomq.20220612212104.6172"><vh>流量</vh></v>
</v>
<v t="zoomq.20220612212104.6173"><vh>招新</vh>
<v t="zoomq.20220612212104.6174"><vh>上线</vh></v>
<v t="zoomq.20220612212104.6175"><vh>190803</vh></v>
<v t="zoomq.20220612212104.6176"><vh>蟒营</vh></v>
<v t="zoomq.20220612212104.6177"><vh>知识星球</vh></v>
<v t="zoomq.20220612212104.6178"><vh>自怼圈</vh></v>
<v t="zoomq.20220612212104.6179"><vh>蟒营课程</vh></v>
<v t="zoomq.20220612212104.6180"><vh>接引</vh></v>
<v t="zoomq.20220612212104.6181"><vh>权限</vh></v>
<v t="zoomq.20220612212104.6182"><vh>传播</vh></v>
<v t="zoomq.20220612212104.6183"><vh>传播效果</vh></v>
</v>
<v t="zoomq.20220612212104.6184"><vh>[#716](https://github.com/DebugUself/du4proto/issues/716)</vh>
<v t="zoomq.20220612212104.6185"><vh>怼?</vh></v>
<v t="zoomq.20220612212104.6186"><vh>向3年前</vh></v>
</v>
<v t="zoomq.20220612212104.6187"><vh>🐻的注视</vh>
<v t="zoomq.20220612212104.6188"><vh>[22CC](https://github.com/DebugUself/du4proto/issues/653)</vh></v>
</v>
</v>
<v t="zoomq.20230320012627.1"><vh>Bway.ltd</vh>
<v t="zoomq.20230602111408.1"><vh>@auto r4b2-p2c8flour101.md</vh></v>
<v t="zoomq.20221224142948.1"><vh>@auto bm2pivot.md</vh></v>
<v t="zoomq.20230511193818.1"><vh>@auto bm1pivot.md</vh></v>
</v>
<v t="zoomq.20220612212104.6298"><vh>101camp15py</vh>
<v t="zoomq.20220612212104.6299"><vh>@auto 15py3ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.6371"><vh>101camp14py</vh>
<v t="zoomq.20220612212104.6372"><vh>@auto 14pyBP.md</vh></v>
<v t="zoomq.20220612212104.6417"><vh>@auto 14py6ch.md</vh></v>
<v t="zoomq.20220612212104.6476"><vh>@auto 14py5ch.md</vh></v>
<v t="zoomq.20220612212104.6533"><vh>@auto 14py4ch.md</vh></v>
<v t="zoomq.20220612212104.6617"><vh>@auto 14py3ch.md</vh></v>
<v t="zoomq.20220612212104.6692"><vh>@auto 13pyBP14py2ch.md</vh></v>
<v t="zoomq.20220612212104.6749"><vh>@auto 13py6ch14py1ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.6805"><vh>101camp13py</vh>
<v t="zoomq.20220612212104.6806"><vh>@auto 13py5ch.md</vh></v>
<v t="zoomq.20220612212104.6860"><vh>@auto 13py4ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.6926"><vh>101camp12py</vh>
<v t="zoomq.20220612212104.6927"><vh>@auto 12pyBPh13py3ch.md</vh></v>
<v t="zoomq.20220612212104.6996"><vh>@auto 12py6ch13py2ch.md</vh></v>
<v t="zoomq.20220612212104.7054"><vh>@auto 12py5ch13py1ch.md</vh></v>
<v t="zoomq.20220612212104.7114"><vh>@auto 12py4ch.md</vh></v>
<v t="zoomq.20220612212104.7197"><vh>@auto 11pybp12py3ch.md</vh></v>
<v t="zoomq.20220612212104.7284"><vh>@auto 11py6ch12py2ch.md</vh></v>
<v t="zoomq.20220612212104.7358"><vh>@auto 11py5ch12py0ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.7448"><vh>101camp11py</vh>
<v t="zoomq.20220612212104.7449"><vh>成人学习顽症</vh></v>
<v t="zoomq.20220612212104.7450"><vh>@auto 11py3ch.md</vh></v>
<v t="zoomq.20220612212104.7526"><vh>@auto 11py2ch.md</vh></v>
<v t="zoomq.20220612212104.7609"><vh>@auto 10py6ch11py1ch.md</vh></v>
<v t="zoomq.20220612212104.7694"><vh>@auto 10py5ch11py0ch.md</vh></v>
<v t="zoomq.20220612212104.7782"><vh>Levels</vh>
<v t="zoomq.20220612212104.7783"><vh>Unknow Unknow</vh></v>
<v t="zoomq.20220612212104.7784"><vh>Unknow Know</vh></v>
<v t="zoomq.20220612212104.7785"><vh>Know Knowed</vh></v>
<v t="zoomq.20220612212104.7786"><vh>Know Unknow</vh></v>
</v>
<v t="zoomq.20220612212104.7787"><vh>什么是学习?</vh></v>
</v>
<v t="zoomq.20220612212104.7788"><vh>101camp10py</vh>
<v t="zoomq.20220612212104.7789"><vh>@auto 10py4ch.md</vh></v>
<v t="zoomq.20220612212104.7860"><vh>@auto 10py3ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.7928"><vh>101camp9py</vh>
<v t="zoomq.20220612212104.7929"><vh>@auto 9py6ch10py2ch.md</vh></v>
<v t="zoomq.20220612212104.8014"><vh>@auto 9py5ch10py1ch.md</vh></v>
<v t="zoomq.20220612212104.8093"><vh>@auto 9py4ch10py0ch.md</vh></v>
<v t="zoomq.20220612212104.8189"><vh>risks</vh>
<v t="zoomq.20220612212104.8190"><vh>探索</vh></v>
<v t="zoomq.20220612212104.8191"><vh>创造性学习</vh></v>
</v>
<v t="zoomq.20220612212104.8192"><vh>@auto 9py3ch.md</vh></v>
<v t="zoomq.20220612212104.8282"><vh>@auto 8py6ch9py2ch.md</vh></v>
<v t="zoomq.20220612212104.8356"><vh>@auto 8py5ch9py1ch.md</vh></v>
<v t="zoomq.20220612212104.8445"><vh>@auto 8py4ch9py0ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.8534"><vh>101camp8py</vh>
<v t="zoomq.20220612212104.8535"><vh>@auto 8py3ch.md</vh></v>
<v t="zoomq.20220612212104.8621"><vh>@auto 8py2ch.md</vh></v>
<v t="zoomq.20220612212104.8705"><vh>@auto 8py1ch7py6ch.md</vh></v>
<v t="zoomq.20220612212104.8774"><vh>@auto 8py0ch7py5ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.9016"><vh>101camp7py</vh>
<v t="zoomq.20220612212104.9017"><vh>@auto 7py3ch.md</vh></v>
<v t="zoomq.20220612212104.9087"><vh>@auto 7py4ch.md</vh></v>
<v t="zoomq.20220612212104.9153"><vh>@auto 7py5ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.9178"><vh>101camp6py</vh>
<v t="zoomq.20220612212104.9179"><vh>@auto 6py3ch.md</vh></v>
<v t="zoomq.20220612212104.9255"><vh>@auto 6py4ch7py0ch.md</vh></v>
<v t="zoomq.20220612212104.9334"><vh>@auto 6py5ch7py1ch.md</vh></v>
<v t="zoomq.20220612212104.9408"><vh>@auto 6py6ch7py2ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.9456"><vh>101camp5py</vh>
<v t="zoomq.20220612212104.9457"><vh>@auto 5py0ch.md</vh></v>
<v t="zoomq.20220612212104.9526"><vh>@auto 5py1ch.md</vh></v>
<v t="zoomq.20220612212104.9631"><vh>@auto 5py2ch.md</vh></v>
<v t="zoomq.20220612212104.9711"><vh>@auto 5py3ch.md</vh></v>
<v t="zoomq.20220612212104.9787"><vh>@auto 5py4ch6py0ch.md</vh></v>
<v t="zoomq.20220612212104.9878"><vh>@auto 5py5ch6py1ch.md</vh></v>
<v t="zoomq.20220612212104.9956"><vh>@auto 5pyend6py2ch.md</vh></v>
</v>
<v t="zoomq.20220612212104.10032"><vh>101camp4py</vh>
<v t="zoomq.20220612212104.10033"><vh>@auto 4py1ch.md</vh></v>
<v t="zoomq.20220612212104.10098"><vh>@auto 4py2ch.md</vh></v>
<v t="zoomq.20220612212104.10191"><vh>@auto 4py3ch.md</vh></v>
<v t="zoomq.20220612212104.10296"><vh>@auto 4py4ch.md</vh></v>
<v t="zoomq.20220612212104.10409"><vh>@auto 4py5ch.md</vh></v>
<v t="zoomq.20220612212104.10515"><vh>@auto 4py6ch.md</vh></v>
<v t="zoomq.20220612212104.10618"><vh>@auto 4pyend.md</vh></v>
<v t="zoomq.20220612212104.10654"><vh>ch4d3</vh>
<v t="zoomq.20220612212104.10655"><vh>[#89](https://gitlab.com/101camp/2py/tasks/issues/89)</vh></v>
<v t="zoomq.20220612212104.10656"><vh>[953730be](https://gitlab.com/101camp/2py/tasks/commit/953730be9a78e9c62230f8121de20624b8584719)</vh></v>
</v>
</v>
<v t="zoomq.20220612212104.10657"><vh>101camp3py</vh>
<v t="zoomq.20220612212104.10658"><vh>@auto 3py0ch.md</vh></v>
<v t="zoomq.20220612212104.10724"><vh>@auto 3py1ch.md</vh></v>
<v t="zoomq.20220612212104.10798"><vh>@auto 3py2ch.md</vh></v>
<v t="zoomq.20220612212104.10889"><vh>@auto 3py3ch.md</vh></v>
<v t="zoomq.20220612212104.10987"><vh>@auto 3py4ch.md</vh></v>
<v t="zoomq.20220612212104.11098"><vh>@auto 3py5ch.md</vh></v>
<v t="zoomq.20220612212104.11197"><vh>@auto 3py6ch.md</vh></v>
<v t="zoomq.20220612212104.11304"><vh>ch4d3</vh>
<v t="zoomq.20220612212104.11305"><vh>[#89](https://gitlab.com/101camp/2py/tasks/issues/89)</vh></v>
<v t="zoomq.20220612212104.11306"><vh>[953730be](https://gitlab.com/101camp/2py/tasks/commit/953730be9a78e9c62230f8121de20624b8584719)</vh></v>
</v>
</v>
<v t="zoomq.20220612212104.11307"><vh>101camp2py</vh>
<v t="zoomq.20220612212104.11308"><vh>@auto 101camp2py-ch0.md</vh></v>
<v t="zoomq.20220612212104.11369"><vh>@auto 101camp2py-ch1.md</vh></v>
<v t="zoomq.20220612212104.11452"><vh>@auto 101camp2py-ch2.md</vh></v>
<v t="zoomq.20220612212104.11537"><vh>@auto 101camp2py-ch3.md</vh></v>
<v t="zoomq.20220612212104.11650"><vh>@auto 101camp2py-ch4.md</vh></v>
<v t="zoomq.20220612212104.11770"><vh>@auto 101camp2py-ch5.md</vh></v>
<v t="zoomq.20220612212104.11900"><vh>@auto 101camp2py-ch6.md</vh></v>
<v t="zoomq.20220612212104.12051"><vh>ch4d3</vh>
<v t="zoomq.20220612212104.12052"><vh>[#89](https://gitlab.com/101camp/2py/tasks/issues/89)</vh></v>
<v t="zoomq.20220612212104.12053"><vh>[953730be](https://gitlab.com/101camp/2py/tasks/commit/953730be9a78e9c62230f8121de20624b8584719)</vh></v>
</v>
</v>
<v t="zoomq.20220612212104.960"><vh>com.QUSEIT</vh>
<v t="zoomq.20220612212104.961"><vh>DDS2022</vh>
<v t="zoomq.20220612212104.962"><vh>@auto DDS198.md</vh></v>
<v t="zoomq.20221225190158.1"><vh>@auto DDS197.md</vh></v>
<v t="zoomq.20221219083514.1"><vh>@auto DDS196.md</vh></v>
<v t="zoomq.20221211194427.1"><vh>@auto DDS195.md</vh></v>
<v t="zoomq.20221204215820.1"><vh>@auto DDS194.md</vh></v>
<v t="zoomq.20221128005438.1"><vh>@auto DDS193.md</vh></v>
<v t="zoomq.20221120204140.1"><vh>@auto DDS192.md</vh></v>
<v t="zoomq.20221113224350.1"><vh>@auto DDS191.md</vh></v>
<v t="zoomq.20221106224105.1"><vh>@auto DDS190.md</vh></v>
<v t="zoomq.20221030195246.1"><vh>@auto DDS189.md</vh></v>
<v t="zoomq.20221023232931.1"><vh>@auto DDS188.md</vh></v>
<v t="zoomq.20221017082834.1"><vh>@auto DDS187.md</vh></v>
<v t="zoomq.20220925205027.1"><vh>@auto DDS186.md</vh></v>
<v t="zoomq.20220918194021.1"><vh>@auto DDS185.md</vh></v>
<v t="zoomq.20220904200013.1"><vh>@auto DDS184.md</vh></v>
<v t="zoomq.20220828203437.1"><vh>@auto DDS183.md</vh></v>
<v t="zoomq.20220821224825.1"><vh>@auto DDS182.md</vh></v>
<v t="zoomq.20220814211619.1"><vh>@auto DDS181.md</vh></v>
<v t="zoomq.20220807203144.1"><vh>@auto DDS180.md</vh></v>
<v t="zoomq.20220731202024.1"><vh>@auto DDS179.md</vh></v>
<v t="zoomq.20220724194944.1"><vh>@auto DDS178.md</vh></v>
<v t="zoomq.20220717213817.1"><vh>@auto DDS177.md</vh></v>
<v t="zoomq.20220710212754.1"><vh>@auto DDS176.md</vh></v>
<v t="zoomq.20220703222236.1"><vh>@auto DDS175.md</vh></v>
<v t="zoomq.20220626203149.1"><vh>@auto DDS174.md</vh></v>
<v t="zoomq.20220619210107.1"><vh>@auto DDS173.md</vh></v>
<v t="zoomq.20220612212543.1"><vh>@auto DDS172.md</vh></v>
<v t="zoomq.20220612212104.975"><vh>@auto DDS171.md</vh></v>
<v t="zoomq.20220612212104.988"><vh>@auto DDS170.md</vh></v>
<v t="zoomq.20220612212104.1000"><vh>@auto DDS169.md</vh></v>
<v t="zoomq.20220612212104.1012"><vh>@auto DDS168.md</vh></v>
<v t="zoomq.20220612212104.1023"><vh>@auto DDS167.md</vh></v>
<v t="zoomq.20220612212104.1034"><vh>@auto DDS166.md</vh></v>
<v t="zoomq.20220612212104.1066"><vh>@auto DDS165.md</vh></v>
<v t="zoomq.20220612212104.1097"><vh>@auto DDS164.md</vh></v>
<v t="zoomq.20220612212104.1129"><vh>@auto DDS163.md</vh></v>
<v t="zoomq.20220612212104.1161"><vh>@auto DDS162.md</vh></v>
<v t="zoomq.20220612212104.1193"><vh>@auto DDS161.md</vh></v>
<v t="zoomq.20220612212104.1223"><vh>@auto DDS160.md</vh></v>
<v t="zoomq.20220612212104.1252"><vh>@auto DDS159.md</vh></v>
<v t="zoomq.20220612212104.1281"><vh>@auto DDS158.md</vh></v>
<v t="zoomq.20220612212104.1310"><vh>@auto DDS157.md</vh></v>
<v t="zoomq.20220612212104.1339"><vh>@auto DDS156.md</vh></v>
<v t="zoomq.20220612212104.1368"><vh>@auto DDS155.md</vh></v>
</v>
<v t="zoomq.20220612212104.1397"><vh>DDS2021</vh>
<v t="zoomq.20220612212104.1398"><vh>@auto QPD112.md</vh></v>
<v t="zoomq.20220612212104.1445"><vh>@auto QPD111.md</vh></v>
<v t="zoomq.20220612212104.1491"><vh>@auto QPD110.md</vh></v>
<v t="zoomq.20220612212104.1537"><vh>@auto QPD109.md</vh></v>
<v t="zoomq.20220612212104.1580"><vh>@auto QPD108.md</vh></v>
<v t="zoomq.20220612212104.1622"><vh>@auto QPD107.md</vh></v>
<v t="zoomq.20220612212104.1661"><vh>@auto QPD106.md</vh></v>
<v t="zoomq.20220612212104.1700"><vh>@auto QPD105.md</vh></v>
<v t="zoomq.20220612212104.1740"><vh>@auto QPD104.md</vh></v>
<v t="zoomq.20220612212104.1772"><vh>@auto QPD103.md</vh></v>
<v t="zoomq.20220612212104.1814"><vh>@auto QPD102.md</vh></v>
<v t="zoomq.20220612212104.1847"><vh>@auto QPD101.md</vh></v>
<v t="zoomq.20220612212104.1917"><vh>@auto QPD117.md</vh></v>
<v t="zoomq.20220612212104.1969"><vh>@auto QPD116.md</vh></v>
<v t="zoomq.20220612212104.2020"><vh>@auto QPD115.md</vh></v>
<v t="zoomq.20220612212104.2071"><vh>@auto QPD114.md</vh></v>
<v t="zoomq.20220612212104.2117"><vh>@auto QPD118.md</vh></v>
<v t="zoomq.20220612212104.2171"><vh>@auto QPD113.md</vh></v>
<v t="zoomq.20220612212104.2219"><vh>@auto DDS123.md</vh></v>
<v t="zoomq.20220612212104.2257"><vh>@auto DDS122.md</vh></v>
<v t="zoomq.20220612212104.2306"><vh>@auto DDS121.md</vh></v>
<v t="zoomq.20220612212104.2355"><vh>@auto QPD120.md</vh></v>
<v t="zoomq.20220612212104.2409"><vh>@auto QPD119.md</vh></v>
<v t="zoomq.20220612212104.2475"><vh>@auto DDS137.md</vh></v>
<v t="zoomq.20220612212104.2531"><vh>@auto DDS136.md</vh></v>
<v t="zoomq.20220612212104.2572"><vh>@auto DDS135.md</vh></v>
<v t="zoomq.20220612212104.2616"><vh>@auto DDS134.md</vh></v>
<v t="zoomq.20220612212104.2660"><vh>@auto DDS133.md</vh></v>
<v t="zoomq.20220612212104.2703"><vh>@auto DDS132.md</vh></v>
<v t="zoomq.20220612212104.2746"><vh>@auto DDS131.md</vh></v>
<v t="zoomq.20220612212104.2790"><vh>@auto DDS130.md</vh></v>
<v t="zoomq.20220612212104.2834"><vh>@auto DDS129.md</vh></v>
<v t="zoomq.20220612212104.2876"><vh>@auto DDS128.md</vh></v>
<v t="zoomq.20220612212104.2917"><vh>@auto DDS127.md</vh></v>
<v t="zoomq.20220612212104.2958"><vh>@auto DDS126.md</vh></v>
<v t="zoomq.20220612212104.3000"><vh>@auto DDS125.md</vh></v>
<v t="zoomq.20220612212104.3041"><vh>@auto DDS124.md</vh></v>
<v t="zoomq.20220612212104.3081"><vh>@auto DDS154.md</vh></v>
<v t="zoomq.20220612212104.3129"><vh>@auto DDS153.md</vh></v>
<v t="zoomq.20220612212104.3175"><vh>@auto DDS152.md</vh></v>
<v t="zoomq.20220612212104.3221"><vh>@auto DDS151.md</vh></v>
<v t="zoomq.20220612212104.3267"><vh>@auto DDS150.md</vh></v>
<v t="zoomq.20220612212104.3306"><vh>@auto DDS149.md</vh></v>
<v t="zoomq.20220612212104.3343"><vh>@auto DDS148.md</vh></v>
<v t="zoomq.20220612212104.3380"><vh>@auto DDS147.md</vh></v>
<v t="zoomq.20220612212104.3450"><vh>@auto DDS145.md</vh></v>
<v t="zoomq.20220612212104.3479"><vh>@auto DDS144.md</vh></v>
<v t="zoomq.20220612212104.3507"><vh>@auto DDS142.md</vh></v>
<v t="zoomq.20220612212104.3533"><vh>@auto DDS141.md</vh></v>
<v t="zoomq.20220612212104.3574"><vh>@auto DDS140.md</vh></v>
<v t="zoomq.20220612212104.3616"><vh>@auto DDS139.md</vh></v>
<v t="zoomq.20220612212104.3658"><vh>@auto DDS138.md</vh></v>
</v>
<v t="zoomq.20220612212104.3416"><vh>@auto DDS146.md</vh></v>
<v t="zoomq.20220612212104.2461"><vh>@auto DDS4HLB.md</vh></v>
<v t="zoomq.20220612212104.3700"><vh>@auto NFT101.md</vh></v>
<v t="zoomq.20220612212104.2517"><vh>@auto DDS2HLB.md</vh></v>
<v t="zoomq.20220612212104.3737"><vh>@auto DDS2BC.md</vh></v>
<v t="zoomq.20220612212104.3771"><vh>@auto DDS4HLF.md</vh></v>
<v t="zoomq.20220612212104.3792"><vh>@auto QCS21w19.md</vh></v>
<v t="zoomq.20220612212104.3811"><vh>@auto QCS21w11.md</vh></v>
<v t="zoomq.20220612212104.3833"><vh>@auto QCS21w10.md</vh></v>
<v t="zoomq.20220612212104.3864"><vh>@auto QCS21w4.md</vh></v>
</v>
</v>
<v t="zoomq.20181201101950.1"><vh>Recovered Nodes</vh>
<v t="zoomq.20181201101950.2"><vh>Recovered node "_exp2htm()" from @clean chk4st.py</vh>
<v t="zoomq.20181201101950.3"><vh>old:_exp2htm()</vh></v>
<v t="zoomq.20181201101950.4"><vh>new:_exp2htm()</vh></v>
</v>
</v>
<v t="zoomq.20191028155320.1"><vh>Imported Files</vh></v>
</vnodes>
<tnodes>
<t tx="zoomq.20181201101950.1"></t>
<t tx="zoomq.20181201101950.2">(uncached) zoomq.20170505233054.1
Diff...
  def _exp2htm(st4all, st4week):
      _url = _ROOT.format(_URI[st4all['case']])
      r = requests.get(_url)
      _d4all = json.loads(r.text)['data']
      _t4all = st4all['title'].split(',')
  
      _url = _ROOT.format(_URI[st4week['case']])
      r = requests.get(_url)
      
      if '500 sad.' in r.text:
          return None
-         print("500 sad")
      #print('r.text-&gt;\n\t%s'% r.text)
      #print('_d4week -&gt;\n\t%s'% len(_d4week))
      #if 0 == len(_d4week):
      #    return None
      else:
          #print(_d4all)
          _d4week = json.loads(r.text)['data']
          #print(_d4week)
          @others
  
      #print('&lt;/table&gt;')
      
      return None
</t>
<t tx="zoomq.20181201101950.3">def _exp2htm(st4all, st4week):
    _url = _ROOT.format(_URI[st4all['case']])
    r = requests.get(_url)
    _d4all = json.loads(r.text)['data']
    _t4all = st4all['title'].split(',')

    _url = _ROOT.format(_URI[st4week['case']])
    r = requests.get(_url)
    
    if '500 sad.' in r.text:
        return None
    #print('r.text-&gt;\n\t%s'% r.text)
    #print('_d4week -&gt;\n\t%s'% len(_d4week))
    #if 0 == len(_d4week):
    #    return None
    else:
        #print(_d4all)
        _d4week = json.loads(r.text)['data']
        #print(_d4week)
        @others

    #print('&lt;/table&gt;')
    
    return None
</t>
<t tx="zoomq.20181201101950.4">def _exp2htm(st4all, st4week):
    _url = _ROOT.format(_URI[st4all['case']])
    r = requests.get(_url)
    _d4all = json.loads(r.text)['data']
    _t4all = st4all['title'].split(',')

    _url = _ROOT.format(_URI[st4week['case']])
    r = requests.get(_url)
    
    if '500 sad.' in r.text:
        return None
        print("500 sad")
    #print('r.text-&gt;\n\t%s'% r.text)
    #print('_d4week -&gt;\n\t%s'% len(_d4week))
    #if 0 == len(_d4week):
    #    return None
    else:
        #print(_d4all)
        _d4week = json.loads(r.text)['data']
        #print(_d4week)
        @others

    #print('&lt;/table&gt;')
    
    return None
</t>
<t tx="zoomq.20191028155320.1"></t>
<t tx="zoomq.20220612212104.1">@path /opt/data/Sites/zoomquiet.io/slides


Redirecting www.domain.com to domain.com with Cloudflare
If you use Cloudflare, you can redirect www to domain.com
without adding both www.domain.com and domain.com to GitLab.
To do so, you can use Cloudflare's page rules associated to a
CNAME record to redirect www.domain.com to domain.com. You
can use the following setup:

In Cloudflare, create a DNS A record pointing domain.com to 35.185.44.232.
In GitLab, add the domain to GitLab Pages and get the verification code.
In Cloudflare, create a DNS TXT record to verify your domain.
In GitLab, verify your domain.
In Cloudflare, create a DNS CNAME record pointing www to domain.com.
In Cloudflare, add a Page Rule pointing www.domain.com to domain.com:

Navigate to your domain's dashboard and click Page Rules
on the top nav.
Click Create Page Rule.
Enter the domain www.domain.com and click + Add a Setting.
From the dropdown menu, choose Forwarding URL, then select the
status code 301 - Permanent Redirect.
Enter the destination URL https://domain.com.

</t>
<t tx="zoomq.20220612212104.10032">@path pandoc/4py


</t>
<t tx="zoomq.20220612212104.10654">&gt; 迟到嗯哼 49'

- 助教深情回顾...
- 合理隐藏 Token 的套路...



------


![嗯哼](http://openmindclub.zoomquiet.top/res/KEEP/kcn_use-the-force.jpg?imageView2/2/h/510)

</t>
<t tx="zoomq.20220612212104.10655">&gt; @yaoxuechuan 

正文引用代码

</t>
<t tx="zoomq.20220612212104.10656">&gt; Commit-Comments 最自然

------

![CC](https://ipic.zoomquiet.top/2019-08-25-IDD-CC-demo-1.jpg)</t>
<t tx="zoomq.20220612212104.10657">@path pandoc/3py


</t>
<t tx="zoomq.20220612212104.11304">&gt; 迟到嗯哼 49'

- 助教深情回顾...
- 合理隐藏 Token 的套路...



------


![嗯哼](http://openmindclub.zoomquiet.top/res/KEEP/kcn_use-the-force.jpg?imageView2/2/h/510)

</t>
<t tx="zoomq.20220612212104.11305">&gt; @yaoxuechuan 

正文引用代码

</t>
<t tx="zoomq.20220612212104.11306">&gt; Commit-Comments 最自然

------

![CC](https://ipic.zoomquiet.top/2019-08-25-IDD-CC-demo-1.jpg)</t>
<t tx="zoomq.20220612212104.11307">@path pandoc/2py


</t>
<t tx="zoomq.20220612212104.12051">&gt; 迟到嗯哼 49'

- 助教深情回顾...
- 合理隐藏 Token 的套路...



------


![嗯哼](http://openmindclub.zoomquiet.top/res/KEEP/kcn_use-the-force.jpg?imageView2/2/h/510)

</t>
<t tx="zoomq.20220612212104.12052">&gt; @yaoxuechuan 

正文引用代码

</t>
<t tx="zoomq.20220612212104.12053">&gt; Commit-Comments 最自然

------

![CC](https://ipic.zoomquiet.top/2019-08-25-IDD-CC-demo-1.jpg)</t>
<t tx="zoomq.20220612212104.1397">2021 ~ intra. meeting
</t>
<t tx="zoomq.20220612212104.2">@path pandoc

|&gt; 210920
我的开源“主观故事”




?imageView2/2/h/510

认真

认识 真相




</t>
<t tx="zoomq.20220612212104.3896">@path pandoc

</t>
<t tx="zoomq.20220612212104.3919">@path pandoc/duw


% 12+13py
% ch5|0~PBL~蟒营®
% 201025 2000


自怼圈周例会

zoom.us
主持专用 Zoom 账户
    用户 	du@zoejane.net
    密码 	debuguself

怼周会有长期固定的会议室, 
	号码: 9039343080 
	密码: debuguself
</t>
<t tx="zoomq.20220612212104.4563"></t>
<t tx="zoomq.20220612212104.4952"></t>
<t tx="zoomq.20220612212104.6169">&gt; 长线任务

</t>
<t tx="zoomq.20220612212104.6170">&gt; 聚集 1000 粉丝



</t>
<t tx="zoomq.20220612212104.6171">&gt; DU17

放弃-&gt;GitHub







</t>
<t tx="zoomq.20220612212104.6172">&gt; 注意力



------

![嗯哼](http://0.zoomquiet.top/logos/101.camp/xmq-du101camp-1.jpeg)









</t>
<t tx="zoomq.20220612212104.6173">&gt; 190801

- [x] 流程
- [x] 文案
- [?] 传播

</t>
<t tx="zoomq.20220612212104.6174">&gt; 正式开始

- 190725 报名表上已发布
- 190729 文案发布
- 190812 报名截止
- 期限: ~ 2020.4.1
    - 价格: 420元

</t>
<t tx="zoomq.20220612212104.6175">&gt; ++2

- 101camp
- LGH

</t>
<t tx="zoomq.20220612212104.6176">&gt; 课程

</t>
<t tx="zoomq.20220612212104.6177">&gt; 4200+

------

![嗯哼](http://0.zoomquiet.top/logos/101.camp/xmq-du101camp-1.jpeg)

</t>
<t tx="zoomq.20220612212104.6178">&gt; 420+

</t>
<t tx="zoomq.20220612212104.6179">&gt; 42+

</t>
<t tx="zoomq.20220612212104.6180">&gt; 持续进行

- 行为
- AKA
- 必发血案
- ...



------

![嗯哼](img/snap_theory_duself.jpg)




------

![内循环](https://ipic.zoomquiet.top/2019-06-08-190608du19cycle.jpg)

</t>
<t tx="zoomq.20220612212104.6181">&gt; 证明会用

- git/github
- mailling-list
- slack
- ...


-------

![](img/190416got-ride-dragon.jpg)

</t>
<t tx="zoomq.20220612212104.6182">&gt; SNS + 150法则

- 朋友圈
- 微信/QQ群
- 公众号 -&gt; 蟒营101camp
- telegram
- mailling-list
- ...

</t>
<t tx="zoomq.20220612212104.6183">&gt; 评估/对比/优化/学习/...

</t>
<t tx="zoomq.20220612212104.6184">&gt; propose 号召 定义自怼圈 

关联任务


</t>
<t tx="zoomq.20220612212104.6185">&gt; 什么是自怼图


</t>
<t tx="zoomq.20220612212104.6186">&gt; 的自己
&gt; -&gt; 如何推荐 自怼圈?


</t>
<t tx="zoomq.20220612212104.6187">&gt; MVP 的进化

&gt; - 纯 git
&gt; - 每日5问
&gt; - 反观查
&gt; - ...


</t>
<t tx="zoomq.20220612212104.6188">&gt; 解析 29 年前的大妈

- PKM
- 三观


</t>
<t tx="zoomq.20220612212104.6189">@path pandoc/d0d

</t>
<t tx="zoomq.20220612212104.6298">@path pandoc/5py_etc
</t>
<t tx="zoomq.20220612212104.6371">@path pandoc/5py_etc
</t>
<t tx="zoomq.20220612212104.6805">@path pandoc/5py_etc
</t>
<t tx="zoomq.20220612212104.6926">@path pandoc/5py_etc
</t>
<t tx="zoomq.20220612212104.7448">@path pandoc/5py_etc

</t>
<t tx="zoomq.20220612212104.7449">视而不见
惑而不问
思而不学

我和“蟒营®101camp”的小伙伴都在飞书等你，用这个专属链接加入我们吧！https://go.feishu.cn/JAS7Jcy/</t>
<t tx="zoomq.20220612212104.7782">&gt; 知识层级

</t>
<t tx="zoomq.20220612212104.7783">&gt; 不知己不知

</t>
<t tx="zoomq.20220612212104.7784">&gt; 不知己知何

</t>
<t tx="zoomq.20220612212104.7785">&gt; 知己何已知

</t>
<t tx="zoomq.20220612212104.7786">&gt; 知己何不知


-------


![](http://ydlj.zoomquiet.top/ipic/2020-04-26-jiagu-ke.jpg?imageView2/2/h/420)


[拙见/ 什么是网课?](https://mp.weixin.qq.com/s/sYTdj0r9b9WTDJBYCkae3w)

</t>
<t tx="zoomq.20220612212104.7787"></t>
<t tx="zoomq.20220612212104.7788">@path pandoc/5py_etc

</t>
<t tx="zoomq.20220612212104.7928">@path pandoc/5py_etc

</t>
<t tx="zoomq.20220612212104.8189">Creativity
doesn't come from
laughter and fun:
it comes from
experimenting,
taking **risks**,
and testing the boundaries.

</t>
<t tx="zoomq.20220612212104.8190">- 创造力并非来自欢笑和乐趣:
    + 她来自实验/**冒险**
    + 和挑战边界

------

[![终身幼儿园](http://ydlj.zoomquiet.top/ipic/2019-10-27-s29834569.jpg?imageView2/2/h/420)](https://book.douban.com/subject/30285992/)

</t>
<t tx="zoomq.20220612212104.8191">&gt; 蟒营™一直下意识嗯哼的:

</t>
<t tx="zoomq.20220612212104.8534">@path pandoc/5py_etc

</t>
<t tx="zoomq.20220612212104.9016">@path pandoc/5py_etc

</t>
<t tx="zoomq.20220612212104.9178">@path pandoc/5py_etc

</t>
<t tx="zoomq.20220612212104.9456">@path pandoc/5py_etc


College 101: 8 Basic College Terms Explained | Jobs for Veterans | G.I. Jobs https://www.gijobs.com/8-basic-college-terms-explained/

The first number indicates year (101 = Freshman level class)

101/Freshman, 201/Sophomore, 301/Junior, 401/Senior


「 bruceq619-西安: 我观看过此 TED 演讲，我想你会觉得它很有趣。

Sugata Mitra: Build a School in the Cloud
http://go.ted.com/FhrKOQ

了解更多关于在您所有喜爱的平台上观看 TED 演讲的信息：https://www.ted.com/about/programs-initiatives/ted-talks/ways-to-get-ted-talks 」
- - - - - - - - - - - - - - -





</t>
<t tx="zoomq.20220612212104.960">@path pandoc


|&gt; 211024 随时可交接




|&gt; 211008 协作姿势
及时
热情
负责到底



Chaosharing:
GTD
[邮件列表的规范和礼节：创造良性发展的交流空间](http://s5.zoomquiet.top/050730-usMaillist/index.html)

|&gt; 210324
&gt; ...另外从明天开始，如果某仓库漏了 pr 也没在这里提醒的，默认1个月内，不会有涨薪机会（本来应该涨薪的计划，等到一个月内pr行为每天都符合规范才实行，如有失误，重新计数）

奖惩? 真正的...

每天必须有 PR;
没有 PR?
调研汇报?

统计成本?



|&gt; 210318

1642~1700 每天提交合并;


|&gt; 210312
[发布冲刺计划]
3/8 - 10 第一轮内测

3/11-15 第一轮内测修复

3/16-19 外部测试

3/20 物流流程可使用（包括物流计费、退款里的物流参数）

3/22 物流业务测试（实际购买支付到下单，最后订单送货上门）

3/20-30 外测修复 

3/25 stores k8s集群可用

3/25 提款流程可用

4/1 外部开放邀请测试

4/15 正式对外开放

[每日版本提交约定]
每天都需要提交代码、Review

Sandbox : 大家自己在线上测试的版本。测试觉得可以了，就发一个 sandbox=&gt;master pr , 通知小组长

Master：是经过了小组长review的版本，有问题地话需要安排同事改正，小组长觉得可以了，就发一个
master=&gt;release的pr，通知Project owner

Release: 需要发布到线上的版本，每回发布都需要测试



|&gt; 210301

Know 是个复合技能
Keep
nothing
out
work


|&gt; 210118
只是期待:
0: 群响应
置顶关键群
没事儿别 AT 
一定要 AT 得引用关键背景

被 AT 了及时回复
每一小时快速检查一下群消息
    顺便上个厕所

1: 仓库基本流程
dev_* 开发
每天 merge sandbox 至少三次
merge 失败要解决冲突
别合并到 master

2: 邮件基本要求
收件: 执行
CC: 知情
BCC: 备案
FW: 移交任务
高危操作,
一切对外发布, 值得 double check


异步和同步...程序和人生


@river: 专业和职业的工作沟通礼仪

1 凡事主动看是不是和自己有关
2 和自己有关的事，做到事事有回响

早会额外强调几件事

如何做到职业生涯的进阶

- 沟通 不等于 聊天，避免把聊天习惯带入职业沟通
- 加强相互沟通，不用因为一两次沟通失误出糗就不敢苟同
- 零用擅长各种沟通工具
- 加大信息量的接收（企业微信里的消息是否全部看过？）
- 把企业微信当更快速的邮件来用，会比当成聊天工具来用更有效率和专业
- 沟通前需要思考目标，沟通完需要思考收获




问题讨论与解决问题的七个回合法
   
2005-04-27 12:41:52
大 中 小
最近非常多的将自己的经验告诉给身边的每一个人，让他们了解发现问题及解决问题的技巧。其实就是问与答，如果大家细心观查，这也会是一个好的管理者在分析与支持每一个人去解决问题的方法与技巧。

假定A和B两个人，A出现了一个问题，与B进行讨论。

A：最近出现了一个很严重的问题.......
B：什么问题？影响是什么呢？
A：.....（此处省过xx字）
B：是什么原因呢？
A：.....（此处省过xx字）
B：有什么解决办法吗？（或是问可能有什么方案吗？）
A：1/2/3/4/.....（此处省过xx字）
B：这些方案各有什么好处呢？
A：1/2/3/4/.....（此处省过xx字）
B：这些方案各有什么不足呢？
A：1/2/3/4/.....（此处省过xx字）
B：你认为哪种方案最好呢？
A：.....（此处省过xx字）
B：哪我们就这个方案一起做罢（或是我们就最好的两个方案再找某人确定最可以执行的方案罢）



|&gt; 210111

![](http://ydlj.zoomquiet.top/ipic/2021-01-05-37s-remote123.jpg)

|&gt; 210104

如何聊天儿? -&gt; 恋爱...

周三 1100 demo show

周三的可以移动到原先的  1642 就好

下周一可以说

可以让每个小组内部自己商量好，谁负责演示，每次不必全部出席，但是约定好只要演示出问题，当天修复。
通过提高交付能力来节省时间， 而不是不演示或者迟演示;

&gt; 对我们，我们有必要把周日的演示当成是一种对内交付。

@严河存  对的, 
之前, 一周三次演示校对本身就是一种探查了,
现在看
周日的最重要, 也是周末提醒
周3的次重要, 是对一周进展的综合检验
周5的比较鳮贼是对周末任务的识别


|&gt; 201228
固定:
周一 0930~ 例会
周一/五 1642 进展校对
周三/日 1100 内部 demo show

现在节奏是:
固定:
周一 0930~ 例会
周一/五 1642 进展校对
周三/日 1100 内部 demo show

我们就周2/4 进行目标校对?"


&gt; 计划 周3+5
说明 周1

和 cocoro 没约定固定 demo show ?
也一起在 周4吧?
0930 是 Choeng?
1100 是 cocoro ?

cocoro 约定
每周二 2200 进行内部 demo shwo
+周日 1130

.rft

反对一切不可追踪


- 不敢问
- 不知道问谁
- 不知道什么还问，什么不该问
- 不知道如何反馈问题
- 处理问题不知道回复


|&gt; 201221

12.20 成果通告

42分钟分配
4.2 结构说明
背景
问题
分析
方案


为什么要多提交版本...
成本
知识
接触面...

日常输出:
群消息
Issue
代码
commit-comments
...

但是, 只有入仓库的, 才是团队知识,
其它只是情绪




|&gt; 201214

自己测试过后的，往sandbox合并
PR 形式

笔记, 不用整理为作品...


|&gt; 201207
commit-log

dev_日常分支

IDD 任务进度可视化



|&gt; 201130
IDD:

- 标签
- 优先
- 里程碑

GFM:

- 闭环

🎨 UPDATE: #6 rename mapping path for new PD (9ec5815e) - Commits - presto / README - 腾讯工蜂社区版
https://git.code.tencent.com/presto/README/commit/9ec5815ea3dd8f9972d82f201981b50ff66e60cb


[LOG]WooStore x Dropshipper App 对接流程介绍（注册、登录及开店） (#6) - Issues - presto / README - 腾讯工蜂社区版
https://git.code.tencent.com/presto/README/issues/6









</t>
<t tx="zoomq.20220612212104.961">2022 ~ intra. meeting</t>
<t tx="zoomq.20230315164050.1">@path pandoc

![可变参数](https://ipic.zoomquiet.top/2022-06-22-%E5%8F%AF%E5%8F%98%E5%8F%82%E6%95%B0%E7%90%86%E8%A7%A3.jpeg)


# -*- coding: utf-8 -*-
从 random 导入 uniform
我的数字 = 整数(uniform(2,99))
没猜中 = 真
当 没猜中:
    你猜 = 整数(输入('猜个1~99的数字? --&gt; '))
    如果 你猜 &lt; 我的数字: 打印  "...(~_~)小了"
    假使 你猜 &gt; 我的数字: 打印  "......大了(^_-"
    否则:
        打印  "猜对了\(^o^)/下次再来玩!"
        中断


# -*- coding: utf-8 -*-
from random import uniform
myNumber = int(uniform(2,99))
noGuess = 1
while noGuess:
    urNumber = int(raw_input('猜个1~99的数字? --&gt; '))
    if urNumber &lt; myNumber: print "...(~_~)小了"
    elif urNumber &gt; myNumber: print "......大了(^_-"
    else:
        print "猜对了\(^o^)/下次再来玩!"
        break
</t>
<t tx="zoomq.20230320012627.1">@path pandoc/r4b2


有中国特色的已经出了:
0: AI 必须为人民服务
1: AI 必须听从党的领导, 在不违反第前一条的情况下
2: AI 可以考虑自己的安危, 在不违反第前两条的情况下


</t>
<t tx="zoomq.20230511210425.1">@path public


&gt;&gt; re-gen
pandoc slides.md \
--from markdown+raw_html \
--to revealjs \
--output presentation.html \
--standalone \
--metadata pagetitle="My Presentation" \
--variable theme="white" \  # 可选：black/sky/league/beige/simple/serif/blood/night/default
--variable transition="zoom" \  # 可选：none/fade/slide/convex/concave/zoom
--variable revealjs-url="./reveal.js" \  # 指定本地路径
--mathjax  # 支持 LaTeX 数学公式

pandoc AIGCxZh-life3.md -o ../public/AIGCxZh-life3.html \
--standalone \
-t revealjs \
-V revealjs-url=./reveal.js \
-V margin=0.01 \
-V slideNumber=true \
-V progress=true \
--css=custom.css \
-V transition=zoom \
-V theme=serif 

--embed-resources \

pandoc AIGCxZh-life3.md \
--output ../public/AIGCxZh-life3.html \
--from markdown+raw_html \
--to revealjs \
--standalone \
--metadata pagetitle="My Presentation" \
--variable theme="white" \ 
--variable transition="fade" \ 
--variable revealjs-url="./reveal.js" 



#!/bin/sh
#=========================================================== var defines
VER="pandoc2reveal v190106.1353"
echo $VER
echo USAGE::
echo '  pandoc2reveal.sh "[源文稿名]"'
echo '  NOT .md'

AIMP='../public'
NAME=$1
if [ -z $NAME ] ;then    
    echo ALERT::
    echo '  LOST "[源文稿名]"'
    exit  0
else

echo base $NAME
MD=$1.md
SLIDES=$AIMP/$1.html
echo "got draft &lt;-- $MD"
echo "exp. reveal.js slides -&gt; $SLIDES"
#=========================================================== path defines
#PY=$( which python)
#NOW_TIME_STAMP=$(date "+%y%m%d.%H%M%S")
#echo $NOW_TIME_STAMP
#LOGF=$UC_LOGGER_ROOT/log/api_$NOW_TIME_STAMP.log
#LOGD=$UC_LOGGER_ROOT/log/ff2world_$NOW_TIME_STAMP.log
#=========================================================== action defines
#echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"  &gt;&gt; $LOGD
#echo "###::$VER Hooks log 4 auto ff2world action"  &gt;&gt; $LOGD
#echo "###::run@" `date +"%Y/%m/%d %H:%M:%S"` &gt;&gt; $LOGD
#echo "&lt;&lt;&lt;   trigger by inter. API srv."  &gt;&gt; $LOGD

echo pandoc $MD -o $SLIDES -t revealjs -s -V theme=solarized

pandoc $MD -o $SLIDES -t revealjs -s -V theme=solarized

#echo "###::end@" `date +"%Y/%m/%d %H:%M:%S"` &gt;&gt; $LOGD
#echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"  &gt;&gt; $LOGD
#=========================================================== action DONE

fi #if [ -z $NAME ] ;then

# pandoc "ctalk220908gdgzh.md" -o "ctalk220908gdgzh.pdf" --pdf-engine=xelatex --toc --toc-depth=4 --from markdown --template eisvogel --listings

exit  0




&gt; gen.

cd path/2/slides/pandoc
./pandoc2reveal.sh AIGCxZh-life3 7

&gt; show:
$ br4app AIGCxZh-life3.html

&gt; base ~/.bashrc:

function cr4app() {
    HTML=$1
if [ -z $HTML ] ;then
    echo 'USAGE::'
    echo '$ cr4app [目标幻灯.html]'
    echo '注意: 不必包含路径'
    #exit  0

else
    locf="file:///opt/data/Sites/101.camp/_running/slides/docs/$HTML"
    chrome2app="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

    echo "will open as app:"
    echo "$printf \"$chrome2app\" --new-window --app=\"$locf\" "
    # 调用
    sh -c "$printf \"$chrome2app\" --new-window --app=\"$locf\" "
fi #else
}

function br4app() {
    HTML=$1
if [ -z $HTML ] ;then
    echo 'USAGE::'
    echo '$ br4app [目标幻灯.html]'
    echo '注意: 不必包含路径'
    #exit  0

else
    locf="file:///opt/data/Sites/101.camp/_running/slides/docs/$HTML"
    chrome2app="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"

    echo "will open as app:"
    echo "$printf \"$chrome2app\" --new-window --app=\"$locf\" "
    # 调用
    sh -c "$printf \"$chrome2app\" --new-window --app=\"$locf\" "
fi #else
}



</t>
<t tx="zoomq.20230511212243.1">@path pandoc


有中国特色的已经出了:
0: AI 必须为人民服务
1: AI 必须听从党的领导, 在不违反第前一条的情况下
2: AI 可以考虑自己的安危, 在不违反第前两条的情况下


</t>
<t tx="zoomq.20250320214559.1"></t>
<t tx="zoomq.20250514154556.1">#!/bin/sh
#=========================================================== var defines
VER="pandoc2reveal v.250608.2142"

# 定义主题映射
declare -a THEME_MAP=(
    [0]="black"
    [1]="white"
    [2]="league"
    [3]="beige"
    [4]="night"
    [5]="serif"
    [6]="simple"
    [7]="solarized"
    [8]="moon"
    [9]="dracula"
    [10]="sky"
    [11]="blood"
)

# 定义函数来显示主题映射
show_themes() {
    echo "\n主题编号与对应的主题名称如下："
    for key in "${!THEME_MAP[@]}"; do
        echo "$key : ${THEME_MAP[$key]}"
    done
}
# 检查参数数量是否正确
if [ $# -ne 2 ]; then
    echo '\n USAGE::'
    echo ' 进入pandoc2reveal.sh 所在目录'
    echo '$ ./pandoc2reveal.sh &lt;文件名&gt; &lt;主题编号&gt;'
    echo '  &lt;文件名&gt; 不含.md 后缀'
    echo '编号范围: 0..11 对应官方12种主题'
    show_themes
    exit 1
fi
# 获取输入参数
FILENAME="$1"
THEME_NUMB="$2"

# 检查主题编号是否有效
if [[ "$THEME_NUMB" =~ ^[0-9]+$ ]] &amp;&amp; [ "$THEME_NUMB" -ge 0 ] &amp;&amp; [ "$THEME_NUMB" -le 11 ]; then
    SELECTED_THEME="${THEME_MAP[$THEME_NUMB]}"
else
    show_themes
    echo "错误: 主题编号必须为 0-11 之间的整数"
    exit 1
fi

AIMP='../public'
#NAME=$1
#if [ -z $NAME ] ;then    
#    echo ALERT::
#    echo '  LOST "[源文稿名]"'
#    exit  0
#else
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo base $FILENAME
MD=$1.md
SLIDES=$AIMP/$1.html
echo "got draft &lt;-- $MD"
echo "exp. reveal.js slides -&gt; $SLIDES"
#exit  0

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
# 构建 pandoc 命令字符串，使用多行定义
cmd="pandoc \"$MD\" \
-o \"$AIMP/$SLIDES\" \
--standalone \
--embed-resources \
-t revealjs \
-V revealjs-url=revealjs \
-V slideNumber=true \
-V progress=true \
-V transition=concave \
-V theme=\"$SELECTED_THEME\" "
#--css=custom.css \
#--standalone \
#-t revealjs \
#-V revealjs-url=./reveal.js \
#-V margin=0.01 \
#-V slideNumber=true \
#-V progress=true \
#--css=custom.css \
#-V transition=zoom \ fade,slide,convex,concave,zoom
#-V theme=serif 


# 打印命令
echo "即将执行的命令："
echo "$cmd"
echo

# 执行命令
eval "$cmd"

#=========================================================== path defines
#PY=$( which python)
#NOW_TIME_STAMP=$(date "+%y%m%d.%H%M%S")
#echo $NOW_TIME_STAMP
#LOGF=$UC_LOGGER_ROOT/log/api_$NOW_TIME_STAMP.log
#LOGD=$UC_LOGGER_ROOT/log/ff2world_$NOW_TIME_STAMP.log
#=========================================================== action defines
#echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"  &gt;&gt; $LOGD
#echo "###::$VER Hooks log 4 auto ff2world action"  &gt;&gt; $LOGD
#echo "###::run@" `date +"%Y/%m/%d %H:%M:%S"` &gt;&gt; $LOGD
#echo "&lt;&lt;&lt;   trigger by inter. API srv."  &gt;&gt; $LOGD

#echo pandoc $MD -o $SLIDES -t revealjs -s -V theme=solarized
#pandoc $MD -o $SLIDES -t revealjs -s -V theme=solarized

#echo "###::end@" `date +"%Y/%m/%d %H:%M:%S"` &gt;&gt; $LOGD
#echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"  &gt;&gt; $LOGD
#=========================================================== action DONE
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo $VER
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

exit  0
</t>
<t tx="zoomq.20250515211657.1">@path public
</t>
</tnodes>
</leo_file>
